import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shorts Studio | Agentic YouTube Shorts builder",
  description:
    "Generate hooks, scripts, b-roll cues, captions, hashtags, and posting tactics for high-performing YouTube Shorts in seconds.",
  metadataBase: new URL("https://agentic-f0cf7f54.vercel.app"),
  openGraph: {
    title: "Shorts Studio | Agentic YouTube Shorts builder",
    description:
      "Craft your next viral YouTube Short with autogenerated scripts, transitions, captions, and publishing playbook tailored to your audience.",
    type: "website",
    url: "https://agentic-f0cf7f54.vercel.app",
  },
  twitter: {
    card: "summary_large_image",
    title: "Shorts Studio | Agentic YouTube Shorts builder",
    description:
      "Craft your next viral YouTube Short with autogenerated scripts, transitions, captions, and publishing playbook tailored to your audience.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
